# this is version for docker-compose, not any of the service images below!
version: '3.7'

services:

  mongo_db:
    image: mongo:4.4.16
    container_name: datastore-mongodb
    user: 1000:1000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: datastore
    ports:
      - 27017:27017
    volumes:
      # mapping for the db setup script
      - ./seed:/docker-entrypoint-initdb.d
      # uncomment line below to mount mongodb data to specified host OS directory       
      - ~/datastore/datastore-deployment/var/docker/mongodata:/data/db

  mongo_express:
    image: mongo-express:0.54.0
    container_name: datastore-mongoexpress
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mongo_db

  influxdb:
    image: influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=datastore
      - DOCKER_INFLUXDB_INIT_PASSWORD=datastore
      - DOCKER_INFLUXDB_INIT_ORG=ospreydcs
      - DOCKER_INFLUXDB_INIT_BUCKET=datastore
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=kBhCr542FKn8mQcL9JhUtqqs8mTdSY7mEydJKhtUvvV938q8zScCxjYiJLKXN8aLlKQZ0Bg3kBBGkKznH2d5Fg==
    volumes:
      - ~/datastore/datastore-deployment/var/docker/influxdata:/var/lib/influxdb2:rw
      - ~/datastore/datastore-deployment/var/docker/influxconfig:/etc/influxdb2:rw
    ports:
      - 8086:8086
    container_name: datastore-influxdb

