#!/usr/bin/env bash

# Called from ~/.bashrc via "source ~/datastore/datastore-support/env/datastore-env", sets up environment environment variables for customization etc.

source ~/datastore/datastore-deployment/custom/env/datastore-env-passwd
source ~/datastore/datastore-deployment/custom/env/datastore-env-vars

# add JAVA and MAVEN HOME to PATH
export PATH=$PATH:$JAVA_HOME/bin:$M2_HOME/bin

export DIR_BIN=~/datastore/datastore-support/bin
alias bin="cd $DIR_BIN"
export PATH=$PATH:$DIR_BIN

